"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var controller_1 = require("./app/user/controller");
var app = express();
var port = 8080;
var router = express.Router();
router.get("/users", controller_1.getUsers);
router.get("/users/:id", controller_1.getUserById);
app.use("/api", router);
app.listen(port);
